import React from "react";
import { CheckCircle2, Image as ImageIcon, MapPin } from "lucide-react";
import { useState } from "react";
import GlassCard from "../components/GlassCard";
import { isPasswordAccepted } from "../utils/passwordValidator";

function PuzzleImage({ item, index }) {
  return <div className="grid min-h-36 flex-1 place-items-center overflow-hidden rounded-3xl border border-blue-100 bg-gradient-to-br from-blue-50 via-white to-violet-50 p-4 text-center shadow-sm">{item.src ? <img src={item.src} alt={item.alt || `Puzzle image ${index + 1}`} className="h-full max-h-52 w-full rounded-2xl object-cover" /> : <div><ImageIcon className="mx-auto text-blue-500" size={34} /><p className="mt-3 text-sm font-black uppercase tracking-widest text-blue-700">{item.placeholder || `Image ${index + 1}`}</p></div>}</div>;
}

export default function ImagePuzzleChallenge({ level, onComplete }) {
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  function verify() { if (isPasswordAccepted(password, level.acceptedPasswords)) { setError(""); onComplete(level.id); return; } setError("Final password not accepted. Recheck all city names and the derived password."); }
  return <div className="space-y-6">{level.puzzles.map((puzzle) => <GlassCard key={puzzle.id} className="p-6 md:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center"><div className="lg:w-40"><p className="text-sm font-black uppercase tracking-widest text-violet-600">{puzzle.label}</p><h3 className="mt-2 text-2xl font-black text-slate-950">City Decoder</h3></div><div className="flex flex-col gap-3 md:flex-row md:items-stretch lg:flex-1">{puzzle.images.map((item, index) => <PuzzleImage key={`${puzzle.id}-${index}`} item={item} index={index} />)}<div className="grid place-items-center px-2 text-3xl font-black text-slate-400">= ?</div></div></div><label className="mt-5 block text-sm font-black uppercase tracking-widest text-blue-700">City Name</label><input className="mt-3 w-full rounded-2xl border border-blue-100 bg-white px-5 py-4 text-lg font-bold outline-none ring-blue-100 transition focus:ring-4" placeholder="Enter decoded city name" /></GlassCard>)}<GlassCard className="p-6 md:p-7"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-violet-600 text-white"><MapPin size={24} /></div><div><p className="text-sm font-black uppercase tracking-widest text-blue-700">Final Password</p><p className="text-sm font-semibold text-slate-500">The application does not calculate it. Participants derive it manually.</p></div></div><div className="mt-5 flex flex-col gap-3 md:flex-row"><input value={password} onChange={(e) => setPassword(e.target.value)} onKeyDown={(e) => e.key === "Enter" && verify()} placeholder="Enter final password" className="min-h-14 flex-1 rounded-2xl border border-blue-100 bg-white px-5 py-4 text-lg font-bold outline-none ring-blue-100 transition focus:ring-4" /><button onClick={verify} className="rounded-2xl bg-slate-950 px-8 py-4 font-black text-white shadow-xl transition hover:-translate-y-0.5"><CheckCircle2 size={18} className="mr-2 inline" /> Verify</button></div>{error && <p className="mt-4 rounded-2xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</p>}</GlassCard></div>;
}
