import React from "react";
import { ArrowRight, Crown, Sparkles, Trophy, Users } from "lucide-react";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import GlassCard from "../components/GlassCard";
import { gameConfig } from "../config/gameConfig";

export default function LandingPage({ onStart }) {
  const navigate = useNavigate();
  const [teamName, setTeamName] = useState(localStorage.getItem(gameConfig.storageKeys.team) || "");
  function startAdventure() { const cleanName = teamName.trim(); if (!cleanName) return; onStart(cleanName); navigate("/level/1/brief"); }
  return <main className="premium-bg min-h-screen overflow-hidden text-slate-950"><section className="relative mx-auto grid min-h-screen max-w-7xl items-center gap-12 px-6 py-12 lg:grid-cols-[1.1fr_0.9fr]"><div className="absolute -left-24 top-24 h-64 w-64 rounded-full bg-blue-200/50 blur-3xl" /><div className="absolute -right-24 top-10 h-80 w-80 rounded-full bg-violet-200/55 blur-3xl" /><div className="relative"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/80 px-4 py-2 text-sm font-black uppercase tracking-widest text-blue-700 shadow-sm backdrop-blur-xl"><Sparkles size={16} /> {gameConfig.hero.eyebrow}</div><h1 className="max-w-4xl text-5xl font-black leading-[0.98] tracking-tight text-slate-950 md:text-7xl">🏆 {gameConfig.hero.title}</h1><p className="mt-6 max-w-2xl bg-gradient-to-r from-blue-700 to-violet-700 bg-clip-text text-2xl font-black text-transparent md:text-3xl">{gameConfig.hero.subtitle}</p><div className="mt-9 grid gap-4 sm:grid-cols-3">{gameConfig.hero.highlights.map((item) => <GlassCard key={item} className="p-5"><p className="text-lg font-black text-slate-950">{item}</p><p className="mt-1 text-sm font-medium text-slate-500">Premium event portal</p></GlassCard>)}</div></div><GlassCard className="relative p-8 md:p-10"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-violet-200/70 blur-2xl" /><div className="grid h-16 w-16 place-items-center rounded-3xl bg-gradient-to-br from-blue-600 to-violet-600 text-white shadow-glow"><Crown size={34} /></div><h2 className="mt-7 text-3xl font-black text-slate-950">Start Your Adventure</h2><p className="mt-3 text-base font-medium leading-7 text-slate-600">Register your team and enter a polished championship experience built for fast-paced corporate collaboration.</p><label className="mt-8 block text-sm font-black uppercase tracking-widest text-blue-700">Team Name</label><input value={teamName} onChange={(e) => setTeamName(e.target.value)} onKeyDown={(e) => e.key === "Enter" && startAdventure()} placeholder="Enter Team Name" className="mt-3 w-full rounded-2xl border border-blue-100 bg-white px-5 py-4 text-lg font-bold text-slate-900 outline-none ring-blue-200 transition focus:ring-4" /><button onClick={startAdventure} disabled={!teamName.trim()} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-blue-600 to-violet-600 px-6 py-4 text-lg font-black text-white shadow-glow transition hover:-translate-y-0.5 hover:scale-[1.01] disabled:cursor-not-allowed disabled:opacity-50"><Trophy size={22} /> Start Adventure <ArrowRight size={20} /></button><div className="mt-7 flex items-center gap-3 rounded-2xl bg-blue-50 px-4 py-3 text-sm font-bold text-blue-800"><Users size={18} /> Built for team play, physical clues, digital validation, and event-day pressure.</div></GlassCard></section></main>;
}
