import React from "react";
import { Crown, Medal, Trophy } from "lucide-react";
import { gameConfig } from "../config/gameConfig";
import GlassCard from "../components/GlassCard";
function sortTeams(teams) { return [...teams].sort((a, b) => b.completedLevels !== a.completedLevels ? b.completedLevels - a.completedLevels : b.currentLevel - a.currentLevel); }
export default function Leaderboard({ currentTeam }) {
  const stored = JSON.parse(localStorage.getItem(gameConfig.storageKeys.leaderboard) || "[]");
  const teams = sortTeams([...gameConfig.leaderboardSeed, ...stored]);
  return <main className="premium-bg min-h-screen px-6 py-12"><section className="mx-auto max-w-7xl"><div><p className="text-sm font-black uppercase tracking-[0.34em] text-blue-700">Live Standings</p><h1 className="mt-3 text-5xl font-black text-slate-950">Leaderboard</h1><p className="mt-3 max-w-2xl text-lg font-medium text-slate-600">Podium-style rankings for a premium corporate championship experience.</p></div><div className="mt-10 grid items-end gap-5 lg:grid-cols-3">{teams.slice(0, 3).map((team, index) => { const rankStyles = ["lg:order-2 lg:scale-110", "lg:order-1", "lg:order-3"]; return <GlassCard key={`${team.teamName}-${index}`} className={`p-7 text-center ${rankStyles[index]}`}><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-gradient-to-br from-blue-600 to-violet-600 text-white shadow-glow">{index === 0 ? <Crown size={34} /> : <Medal size={32} />}</div><p className="mt-5 text-4xl font-black text-slate-950">#{index + 1}</p><h2 className="mt-2 text-2xl font-black text-slate-900">{team.teamName}</h2><p className="mt-3 text-sm font-bold uppercase tracking-widest text-blue-700">Level {team.currentLevel}</p><p className="mt-1 text-slate-500">{team.completedLevels} completed levels</p></GlassCard>; })}</div><GlassCard className="mt-12 overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-blue-50 text-sm uppercase tracking-widest text-blue-700"><tr><th className="px-6 py-5">Rank</th><th className="px-6 py-5">Team Name</th><th className="px-6 py-5">Current Level</th><th className="px-6 py-5">Completed Levels</th><th className="px-6 py-5">Status</th></tr></thead><tbody>{teams.map((team, index) => { const isCurrent = currentTeam && team.teamName === currentTeam.teamName; return <tr key={`${team.teamName}-row-${index}`} className={`border-t border-blue-50 ${isCurrent ? "bg-violet-50/70" : "bg-white/60"}`}><td className="px-6 py-5 text-lg font-black text-slate-950">#{index + 1}</td><td className="px-6 py-5 font-black text-slate-900">{team.teamName}</td><td className="px-6 py-5 font-bold text-slate-700">Level {team.currentLevel}</td><td className="px-6 py-5 font-bold text-slate-700">{team.completedLevels}</td><td className="px-6 py-5"><span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-black uppercase tracking-widest ${team.completedLevels >= gameConfig.totalLevels ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"}`}><Trophy size={14} className="mr-1" /> {team.completedLevels >= gameConfig.totalLevels ? "Completed" : "In Progress"}</span></td></tr>; })}</tbody></table></div></GlassCard></section></main>;
}
