import React from "react";
import { CheckCircle2, ClipboardCheck } from "lucide-react";
import { useState } from "react";
import GlassCard from "../components/GlassCard";
import { isPasswordAccepted } from "../utils/passwordValidator";

export default function MCQChallenge({ level, onComplete }) {
  const [answers, setAnswers] = useState({});
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  function updateAnswer(question, option) { if (question.type === "single") { setAnswers((current) => ({ ...current, [question.id]: option })); return; } setAnswers((current) => { const existing = current[question.id] || []; const next = existing.includes(option) ? existing.filter((item) => item !== option) : [...existing, option]; return { ...current, [question.id]: next }; }); }
  function verify() { if (isPasswordAccepted(password, level.acceptedPasswords)) { setError(""); onComplete(level.id); return; } setError("Final password not accepted. The app does not calculate it, so verify your derived password."); }
  return <div className="space-y-6"><GlassCard className="p-6 md:p-7"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-violet-600 text-white"><ClipboardCheck size={24} /></div><div><h2 className="text-2xl font-black text-slate-950">Project Knowledge Challenge</h2><p className="font-semibold text-slate-500">All questions appear on one page. Answer type is controlled by configuration.</p></div></div></GlassCard>{level.questions.map((question, questionIndex) => <GlassCard key={question.id} className="p-6 md:p-7"><div className="flex flex-col gap-5 lg:flex-row"><div className="lg:w-40"><p className="text-sm font-black uppercase tracking-widest text-violet-600">Question {questionIndex + 1}</p><span className="mt-3 inline-block rounded-full bg-blue-50 px-3 py-1 text-xs font-black uppercase tracking-widest text-blue-700">{question.type === "single" ? "Single Choice" : "Multiple Choice"}</span></div><div className="flex-1"><h3 className="text-2xl font-black leading-snug text-slate-950">{question.question}</h3><div className="mt-5 grid gap-3 md:grid-cols-2">{question.options.map((option) => { const isChecked = question.type === "single" ? answers[question.id] === option : (answers[question.id] || []).includes(option); return <label key={option} className={`flex cursor-pointer items-center gap-3 rounded-2xl border px-4 py-4 font-bold transition ${isChecked ? "border-blue-300 bg-blue-50 text-blue-800" : "border-blue-100 bg-white text-slate-700 hover:border-blue-200"}`}><input type={question.type === "single" ? "radio" : "checkbox"} name={question.id} checked={isChecked} onChange={() => updateAnswer(question, option)} className="h-5 w-5 accent-blue-600" />{option}</label>; })}</div></div></div></GlassCard>)}<GlassCard className="p-6 md:p-7"><p className="text-sm font-black uppercase tracking-widest text-blue-700">Final Password</p><p className="mt-1 text-sm font-semibold text-slate-500">Participants manually derive this password. The app does not calculate it from MCQ answers.</p><div className="mt-5 flex flex-col gap-3 md:flex-row"><input value={password} onChange={(e) => setPassword(e.target.value)} onKeyDown={(e) => e.key === "Enter" && verify()} placeholder="Enter final password" className="min-h-14 flex-1 rounded-2xl border border-blue-100 bg-white px-5 py-4 text-lg font-bold outline-none ring-blue-100 transition focus:ring-4" /><button onClick={verify} className="rounded-2xl bg-slate-950 px-8 py-4 font-black text-white shadow-xl transition hover:-translate-y-0.5"><CheckCircle2 size={18} className="mr-2 inline" /> Verify</button></div>{error && <p className="mt-4 rounded-2xl bg-rose-50 px-4 py-3 text-sm font-bold text-rose-700">{error}</p>}</GlassCard></div>;
}
